### ISSUE TITLE
Production issue #1

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/income-tax-mtd-changelog#22]
Production environment
 Bug - API
update Uk property period

* **Which API is the issue related to?**
/individuals/business/property/uk
* **What is the current behaviour?**
ERROR 500

* **What is the expected behaviour?**
success, it works in test

* **Other information** 

2022-10-06T17:09:43.469 INFO put 1 resource=> /individuals/business/property/uk/PB966848A/XJIS00000001249/period/2022-23/f971d75e-497b-4ab4-bf76-1dc1d0182902
2022-10-06T17:09:43.874 INFO put 1 status=500  body={"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}

DATA FOR PUT 
{"ukFhlProperty":{"income":{"periodAmount":"0","taxDeducted":"0","rentARoom":{"rentsReceived":"0"}},"expenses":{"consolidatedExpenses":"0"}},"ukNonFhlProperty":{"income":{"premiumsOfLeaseGrant":"0","reversePremiums":"0","periodAmount":"2430","taxDeducted":"0","otherIncome":"0","rentARoom":{"rentsReceived":"0"}},"expenses":{"consolidatedExpenses":"729.95"}}}

**Comment by abigail-houston-hmrc** [comment]
Currently being addressed by the SDST team

**Comment by alexei-serjantov** [comment]
Why the issue was closed?
It is still present in MTD production environment 16 Oct 2023

2023-10-16T16:09:01.288 INFO put  resource=> /individuals/business/property/uk/PB966848A/XJIS00000001249/period/2023-24/65bc388c-5c75-4434-938f-f84d84c2b0ec headers=> {
  'gov-vendor-license-ids': '',
  'gov-client-browser-do-not-track': 'false',
  'gov-client-screens': 'width=2560&height=1440&scaling-factor=1.3499999046325684&colour-depth=24',
  'gov-client-timezone': 'UTC+01:00',
  'gov-client-connection-method': 'WEB_APP_VIA_SERVER',
  'gov-client-browser-plugins': '',
  'gov-client-window-size': 'width=1764&height=1424',
  'gov-vendor-version': 'SE_reportsServer=2.0&SE_reportsClient=2.0',
  'gov-client-multi-factor': '',
  'gov-client-device-id': '3b5af9a0-32a3-11ee-ab95-37cccb9880b4',
  'gov-client-browser-js-user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
  'gov-client-local-ips': '8b6b7294-a930-48db-9330-9ebf3c3c96f7.local',
  'gov-vendor-public-ip': '81.150.62.73',
  'gov-client-public-ip': '81.150.62.73',
  'gov-client-public-ip-timestamp': '2023-10-16T15:06:27.332Z',
  'gov-client-local-ips-timestamp': '2023-10-16T15:06:27.332Z',
  'gov-vendor-product-name': 'SE_reports',
  'gov-client-public-port': 60702,
  'gov-client-user-ids': 'SE_reportsUser=PB966848A',
  'gov-vendor-forwarded': 'by=81.150.62.73&for=81.150.62.73',
  Accept: 'application/vnd.hmrc.2.0+json',
  Authorization: 'Bearer a2d12e81d507e304146d959ea17a44a2'
}
2023-10-16T16:09:02.156 INFO put  status=500  body={"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}

**Comment by abigail-houston-hmrc** [comment]
The above is a production issue. Such issues are investigated by HMRC's SDST team. Please contact them for more information:
https://developer.service.hmrc.gov.uk/developer/support
